name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test

      - name: Upload Allure results
        run: |
          mkdir -p allure-results
          cp -r ./* allure-results/
        continue-on-error: true

      - name: Generate Allure HTML Report
        run: npx allure-playwright generate --report-dir=allure-report

      - name: Upload Allure HTML Report
        run: |
          mkdir -p allure-report
          cp -r allure-report/* .
        continue-on-error: true
